/*
**  Copyright (c) 2010-2017, Panasonic Corporation.
**
**  Permission to use, copy, modify, and/or distribute this software for any
**  purpose with or without fee is hereby granted, provided that the above
**  copyright notice and this permission notice appear in all copies.
**
**  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
**  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
**  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
**  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
**  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
**  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
**  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/

#include <stdio.h>

#include <dof/inet.h>
#include <dof/oal.h>
#include <dof/dof-aes.h>
#include <dof/reconnectingstatelistener.h>

#include "helloWorldInterface.h"    // This is the file generated by the interface repository, https://interface.opendof.org/interface/opendof/1.00010000/1?2

// Application configuration.
// For convenience, the configuration information is hard coded here.

// Define the host or IP address and port for the connection. 
const char * helloWorldAddress = "127.0.0.1";
const uint16 helloWorldPort = 3567;
const uint32 helloWorldConnectTimeout = 60000;  // 60 seconds

// Set the identity, domain, and key for the credentials here.
// WARNING!!! Defining the credentials in code is not recommended. They are included in this example for convenience of having a portable example.
const char * helloWorldDomain = "[6:example.opendof.org]";
const char * helloWorldIdentity = "[3:user@example.opendof.org]";
const uint8 helloWorldKey[32] = { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 };

// Provider configuration.
const char * helloWorldProviderObjectID = "[{00}:]";    // This is the broadcast objectID, this requestor uses it to look for anyone providing the hello world interface.
const uint32 helloWorldWaitProviderTimeout = 60000;     // 60 seconds

// Helper functions.

// This function is used as a log listener, it is not required but can be useful.
static void DofLogCallback( DOFLogListener self, uint32 timestamp, DOFLogLevel priority, const char * message )
{
    // This function does not use the timestamp and priority parameters.
    (void)timestamp;
    (void)priority;
    
    fprintf(stderr, "LogListener message: %s\n", message);
}

// Create the DOFCredentials that will be used for the application.
// The credentials consist of the domain, identity, and a secret. This application uses key credentials, so a 32 byte key is provided for the secret.
// domain - The domain to use for the credentials. This must not be NULL.
// identity - The identity to use for the credentials. This must not be NULL.
// key - A 32 byte key that holds the secret for the credentials.
static DOFCredentials createCredentials(const char * domain, const char * identity, const uint8 key[32])
{
    DOFCredentials  myCreds = NULL;
    DOFObjectID     objectID = DOFObjectID_Create_StandardString(domain);
    
    if (objectID)
    {
        DOFObjectIDDomain domainID = DOFObjectIDDomain_Create( objectID );
        if (domainID)
        {
            DOFObjectID objectIDAuth = DOFObjectID_Create_StandardString(identity);
            if (objectIDAuth)
            {
                DOFObjectIDAuthentication authID = DOFObjectIDAuthentication_Create( objectIDAuth );
                if (authID)
                {
                    myCreds = DOFCredentialsKey_Create(domainID, authID, key);
                    
                    DOFObjectIDAuthentication_Destroy(authID);
                }
                DOFObjectID_Destroy(objectIDAuth);
            }
            DOFObjectIDDomain_Destroy(domainID);
        }
        DOFObjectID_Destroy(objectID);
    }
    return myCreds;
}

// Wait for the connection to be connected, or the timeout is reached.
// This function will not do anything that will cause the connection to be connected, it will only wait for it to become connected.
// connection - The connection that will be connected.
// timeout - The maximum time in milliseconds to wait for the connection to be connected.
// TRUE is returned as soon as the connection is connected.
// FALSE is returned if the connection is not connected before the timeout is reached.
static boolean waitConnected(DOFConnection connection, uint32 timeout)
{
    uint32 timeRemaining = timeout;
    boolean connected = DOFConnection_IsConnected(connection);
    
    while (!connected && (timeRemaining > 0))
    {
        if (timeRemaining > 500)
        {
            PCRThread_Sleep(500);
            timeRemaining -= 500;
        }
        else
        {
            PCRThread_Sleep(timeRemaining);
            timeRemaining = 0;
        }
        connected = DOFConnection_IsConnected(connection);
    }
    return connected;
}

// Create a DOFConnection. 
// dof - The connection is created based on a dof. This must not be NULL.
// creds - The DOFCredentials that will be used for the connection. This must not be NULL.
// host - The hostname or IP address that the connection will connect to. This must be a valid hostname or IP address.
// port - The port that should be used based on the given hostname. This must be set to a valid port.
//Note: This will not connect the connection.
static DOFConnection createConnection(DOF dof, DOFCredentials creds, const char * host, uint16 port)
{
    DOFAddress addr = NULL;
    DOFConnection conn = NULL;

    addr = InetTransport_CreateAddress(host, port);
    if (addr)
    {
        DOFConnectionConfigBuilder connConfigBuilder =  DOFConnectionConfigBuilder_Create(DOFCONNECTIONTYPE_STREAM, addr);
        if (connConfigBuilder)
        {
            if (DOFConnectionConfigBuilder_SetSecurityDesire(connConfigBuilder, DOFSECURITYDESIRE_SECURE))
            {
                if (DOFConnectionConfigBuilder_SetCredentials(connConfigBuilder, creds))
                {
                    DOFConnectionConfig connConfig = DOFConnectionConfigBuilder_Build(connConfigBuilder);
                    if (connConfig)
                    {
                        conn = DOF_CreateConnection(dof, connConfig);
                        DOFConnectionConfig_Destroy(connConfig);
                    }                
                }
            }
            DOFConnectionConfigBuilder_Destroy(connConfigBuilder);
        }
        DOFAddress_Destroy(addr);
    }
    return conn;
}

// Create a DOFSystem
// dof - The system is created based on a dof. This must not be NULL.
// creds - the DOFCredentials that will be used for the system. This must not be NULL.
static DOFSystem createSystem(DOF dof, DOFCredentials creds)
{
    DOFSystem sys;
    
    DOFSystemConfigBuilder sysConfigBldr = DOFSystemConfigBuilder_Create();
    if (sysConfigBldr)
    {
        if (DOFSystemConfigBuilder_SetCredentials(sysConfigBldr, creds))
        {
            DOFSystemConfig sysConfig = DOFSystemConfigBuilder_Build(sysConfigBldr);
            if (sysConfig)
            {
                sys = DOF_CreateSystem(dof, sysConfig, 5000, NULL);
                DOFSystemConfig_Destroy(sysConfig);
            }
        }
        DOFSystemConfigBuilder_Destroy(sysConfigBldr);
    }
    return sys;
}

int main(int argc, char * argv[])
{
    DOFLogListener_t DOFLogger = { NULL, DofLogCallback };
    
    printf("Running Hello World Requestor.\n");

    // The initialization function for the DOF and InetTransport must be called before any other library functions are called.
    DOF_Init();
    InetTransport_Init();
    
    // Adding a log listener is not required, but can provide useful information.
    if (DOFLog_AddListener(DOFLOGLEVEL_INFO | DOFLOGLEVEL_WARNING | DOFLOGLEVEL_ERROR, &DOFLogger))
    {
        // Secure OpenDOF applications require at least one cipher to be registered, this application uses AES 256.
        if (DOFCipherRegistry_Register(DOFCIPHERALGORITHM_AES, DOFCIPHERSTRENGTH_256, &BlockCipher_AES_256))
        {
            DOFCredentials creds = createCredentials(helloWorldDomain, helloWorldIdentity, helloWorldKey);
            if (creds)
            {
                DOF dof = DOF_Create(NULL);
                if (dof)
                {
                    DOFConnection conn = createConnection(dof, creds, helloWorldAddress, helloWorldPort);
                    if (conn)
                    {
                        // Add the connection to a reconnecting state listener, which will cause it to connect and it and will reconnect it if the connection closes for some reason
                        ReconnectingStateListener reconnectListener = ReconnectingStateListener_Create(NULL);
                        if (reconnectListener)
                        {
                            if (ReconnectingStateListener_AddConnection(reconnectListener, conn) == RECONNECTINGSTATELISTENER_STATUS_SUCCESS)
                            {
                                if (waitConnected(conn, helloWorldConnectTimeout))
                                { 
                                    // Now that the connection is created and connected, send interest and make a request when a provider is found.
                                    DOFSystem sys = createSystem(dof, creds);
                                    if (sys)
                                    {
                                        DOFObjectID objectID = DOFObjectID_Create_StandardString(helloWorldProviderObjectID);
                                        DOFObject obj = DOFSystem_CreateObject(sys, objectID);
                                        DOFInterfaceID helloWorldInterfaceID = DOFInterfaceID_Create_Bytes(sizeof(HELLOWORLD_IDBytes), HELLOWORLD_IDBytes);
                                        DOFInterface helloWorldInterface = DOFInterface_Create(helloWorldInterfaceID, sizeof(HELLOWORLD_Bytes), HELLOWORLD_Bytes);
                                    
                                        if (obj && helloWorldInterface)
                                        {
                                            // Watch level interest will look for anyone providing the hello world interface.
                                            DOFOperation interestOp = DOFSystem_BeginInterest(sys, objectID, helloWorldInterfaceID, DOFINTERESTLEVEL_WATCH, NULL, DOF_TIMEOUT_NEVER, NULL, NULL );
                                            if (interestOp)
                                            {
                                                // Wait until we know someone who is providing the hello world interface.
                                                DOFObject waitObj = DOFSystem_WaitProvider( sys, objectID, 1, &helloWorldInterfaceID, 3000 );
                                                if ( waitObj )
                                                {
                                                    // Now that we know someone who is providing the hello world interface, get the HELLOWORLD_phrase property.
                                                    DOFResult result = DOFObject_Get(waitObj, DOFInterface_GetProperty(helloWorldInterface, HELLOWORLD_phrase), NULL, 5000, NULL );
                                                    if (result)
                                                    {
                                                        // Print the string that was received.
                                                        printf("Received: %s\n", DOFValueString_Get(DOFResult_GetValue(result)));
                                                        DOFResult_Destroy(result);
                                                    }
                                                    DOFObject_Destroy(waitObj);
                                                }
                                                DOFOperation_Destroy(interestOp);
                                            }
                                        }
                                        DOFInterface_Destroy(helloWorldInterface);
                                        DOFInterfaceID_Destroy(helloWorldInterfaceID);
                                        DOFObject_Destroy(obj);
                                        DOFObjectID_Destroy(objectID);
                                        DOFSystem_Destroy(sys);
                                    }
                                }
                                ReconnectingStateListener_RemoveConnection(reconnectListener, conn);                        
                            }
                            ReconnectingStateListener_Destroy(reconnectListener);
                        }                    
                        DOFConnection_Destroy(conn);
                    }
                    DOF_Destroy(dof);
                }
                DOFCredentials_Destroy(creds);
            }
        }
        DOFLog_RemoveListener(&DOFLogger);
    }    

    InetTransport_Shutdown();
    DOF_Shutdown();

    return 0;
}

